Fix test failure with Pytest 4.

Taken from upstream:
https://github.com/chardet/chardet/commit/440828f8faafdb58700c64a9ea8f6a30b154c08b

diff --git a/test.py b/test.py
--- a/test.py
+++ b/test.py
@@ -59,5 +59,5 @@ def gen_test_params():
             full_path = join(path, file_name)
             test_case = full_path, encoding
             if full_path in EXPECTED_FAILURES:
-                test_case = pytest.mark.xfail(test_case)
+                test_case = pytest.param(*test_case, marks=pytest.mark.xfail)
             yield test_case
